name: Build & Publish

on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.HYVOR_ORG_DOCKERHUB_USERNAME }}
          password: ${{ secrets.HYVOR_ORG_DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            hyvor/hyvor-blogs-docker:${{ github.ref_name }}
            hyvor/hyvor-blogs-docker:latest
