name: Build & Publish

on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Debug credentials
        run: |
          echo "Username: ${{ vars.DOCKERHUB_USERNAME }}"
          echo "Token length: ${#DOCKERHUB_TOKEN}"
        env:
          DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            enthupratik/hyvor-blogs-docker:${{ github.ref_name }}
            enthupratik/hyvor-blogs-docker:latest
